### ISSUE TITLE
CdTimerComponent error

### ISSUE THREAD

**Issue by Maryna-Yelakova** [clemdesign/angular-cd-timer#1]
I get that error in browser console
`ERROR TypeError: Cannot read property 'nodeValue' of undefined
    at CdTimerComponent.push../node_modules/angular-cd-timer/cd-timer.js.CdTimerComponent.ngAfterViewInit (cd-timer.js:20)`

here is my code:
`<cd-timer format="hms"></cd-timer>`

**Comment by clemdesign** [comment]
Sorry for the late @Maryna-Yelakova 

Did you resolve your issue? 
Otherwise, what is your configuration? (Angular version...)

Did you use event to hide/show or build `<cd-timer>`component?

**Comment by naveenr2112** [comment]
@clemdesign I tried in Angular version 6.0.7 but got the same error as @Maryna-Yelakova has mentioned.

**Comment by clemdesign** [comment]
@naveenr2112 could you share your `package.json` please? 
I need the `dependencies` and `devDependencies` to use the same configuration.

**Comment by naveenr2112** [comment]
`"scripts": {
    "ng": "ng",
    "start": "ng serve --aot",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/animations": "^6.1.10",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^6.0.7",
    "@angular/compiler": "^6.0.7",
    "@angular/core": "^6.0.7",
    "@angular/flex-layout": "^5.0.0-beta.14",
    "@angular/forms": "^6.0.7",
    "@angular/http": "^6.0.7",
    "@angular/material": "^6.3.3",
    "@angular/platform-browser": "^6.0.7",
    "@angular/platform-browser-dynamic": "^6.0.7",
    "@angular/router": "^6.0.7",
    "@ng-bootstrap/ng-bootstrap": "^4.0.1",
    "@swimlane/ngx-charts": "^7.4.0",
    "angular-font-awesome": "^3.1.2",
    "angular-gantt": "^2.0.0-rc.1",
    "angular-highlight-js": "^2.0.1",
    "angular-nvd3": "^1.0.9",
    "angular-svg-round-progressbar": "^2.0.0",
    "angular2-chartjs": "^0.4.1",
    "angularfire2": "^5.0.0-rc.5-next",
    "bootstrap": "^4.2.1",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.7",
    "d3": "^4.13.0",
    "firebase": "^4.13.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highlight.js": "^9.12.0",
    "leaflet": "^1.2.0",
    "ng2-ace-editor": "^0.3.8",
    "ng2-dnd": "^5.0.2",
    "ng2-nvd3": "^2.0.0",
    "ng2-odometer": "^1.1.3",
    "ng2-page-transition": "^1.1.0",
    "ngx-bootstrap": "^3.1.4",
    "ngx-cookie-service": "^2.1.0",
    "ngx-perfect-scrollbar": "^5.3.5",
    "ngx-quill": "^2.2.0",
    "ngx-spinner": "^6.1.2",
    "ngx-toastr": "^9.1.1",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
    "screenfull": "^3.3.2",
    "vued3tree": "^3.5.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.7",
    "@angular/language-service": "^6.0.7",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^9.6.22",
    "codelyzer": "^4.4.2",
    "jasmine-core": "~2.9.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.3.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.7.2"
  }`

Please find the dependencies and dev dependencies..

**Comment by clemdesign** [comment]
So, after test, the library is not compatible with Angular 6.

I recommend you to use Angular 4 or 5 if you want to use this library.
Otherwise, an analysis shall be done to make compatible but I don't have time for now.

**Comment by clemdesign** [comment]
I close this issue.

**Comment by Maryna-Yelakova** [comment]
@clemdesign Can you please provide compatible Angular versions in your documentation. It may save the time for others

**Comment by clemdesign** [comment]
Okay. Done !

**Comment by clemdesign** [comment]
For information, this component is now compatible with Angular 6 and upper.
See the release [1.0.0](https://github.com/clemdesign/angular-cd-timer/releases/tag/1.0.0).
