### ISSUE TITLE
How to generate an event on particular time

### ISSUE THREAD

**Issue by shreyshahh** [clemdesign/angular-cd-timer#10]
I am starting the timer, now I want to call method on a specific tick count how can I do that. Can I call a method or generate an event on specific tick count. I think I have to continuous get the tick count value and call a method when the specific tick count value comes. Any help on how to do it?

**Comment by clemdesign** [comment]
Hello, with current version, the only solution is to use event `(onTick)`  and call your method when the tick count reach your specific value.
