### ISSUE TITLE
Timer not working for autostart=false

### ISSUE THREAD

**Issue by KeshavKundal** [clemdesign/angular-cd-timer#12]
Timer does not work if we set [autostart]="false", and try to start the timer by:
import { CdTimerComponent } from 'angular-cd-timer';
  @ViewChild('basicTimer', { static: false }) private countUp: CdTimerComponent;
this.countUp.start();

It returns the error: TypeError: Cannot read property 'start' of undefined

Is there anything I am missing here?

**Comment by clemdesign** [comment]
@KeshavKundal what is the version of your Angular ?

Related to "It returns the error: TypeError: Cannot read property 'start' of undefined", check that your  component is not under directive ngIf/ngFor...

**Comment by KeshavKundal** [comment]
Thanks for quickly reverting back on this issue.
Yes, It is under "*ngIf".
I am using this timer for a quiz system, where in For each fetched question we set the endTime as the remaining time for quiz.
When we start fetching the question and initiates an http call, we hide the template containing the timer and show loader. Once it is fetched, we hide the loader and show the template containing the timer component.

**Comment by clemdesign** [comment]
You're not answer my question about Angular version.

For @ViewChild decorator, its doesn't work for components under *ngIf directive: At initialization of your component, all reference shall be reachable if you use @ViewChild.

**Comment by KeshavKundal** [comment]
Using Angular 10.
Yes Without ngif It works, But I need the ngIf to show loader. Any help ?
I tried with [hidden] as well instead of ngIf, It broke the other countdown timer I am using.

**Comment by clemdesign** [comment]
Use a component to wrap `cd-timer` and apply ngIf to this component.
Pass used data to this component and control the timer in this component with @ViewChild.

This issue is an integration problem, so I close it.
