### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by akshaymhari** [clemdesign/angular-cd-timer#15]
How do we import this module in the project ?

**Comment by clemdesign** [comment]
Like a standard [Angular module import](https://angular.io/guide/architecture-modules)

```typescript
import { CdTimerModule } from 'cd-timer';

@NgModule({
  // ...,
  imports: [
    // ...,
    CdTimerModule
  ],
  // ...
})
export class AppModule { }
```

**Comment by akshaymhari** [comment]
<cd-timer format="intelli" countdwon="true" [startTime]="value"></cd-timer> is working as countup timer

**Comment by clemdesign** [comment]
This is not a standalone library but an Angular component as described in README.
