### ISSUE TITLE
CdTimer displays text in a second after page rendering (when first tick occurs)

### ISSUE THREAD

**Issue by yksht** [clemdesign/angular-cd-timer#16]
Hi,
There is a 1-second lag when the timer starts showing the text.
It would be great to render text immediately when all other content shows :)
Here is one line fix for this problem. I already did it.
Should I make a PR? Or maybe you have a reason for this 1-second lag? :)

**Comment by clemdesign** [comment]
According to my remember, it's for specific projet and let other components initializing before start real count.

But you can propose your PR/solution to improve this generic library.

**Comment by yksht** [comment]
This PR doesn't affect any kind of logic. All logic works as it was. It just helps to render the timer immediately.

**Comment by clemdesign** [comment]
OK, I merged the PR and will create a bugfix release.

**Comment by clemdesign** [comment]
New release 1.0.1 will be available in few minutes.

**Comment by yksht** [comment]
@clemdesign Thanks a lot!
