### ISSUE TITLE
angular 8

### ISSUE THREAD

**Issue by karincayazilim** [clemdesign/angular-cd-timer#2]
angular 8 support please!
and install document

**Comment by clemdesign** [comment]
Hi, not planned for now.
If you works on compatibility with Angular 8, I suggest you to propose a pull request.
Thanks!

Best!

**Comment by clemdesign** [comment]
Hi,
Today I worked on this issue.
So, it's now compatible with Angular 6 and upper.
The release is available [here](https://github.com/clemdesign/angular-cd-timer/releases/tag/1.0.0).
Best!

**Comment by karincayazilim** [comment]
used it works very well. Thank you
