### ISSUE TITLE
ViewChild in Angular 8 and cd-timer

### ISSUE THREAD

**Issue by sourjya** [clemdesign/angular-cd-timer#3]
Hi,
   First of all thank you very much for this component. 

From the examples on http://angular-cd-timer.clemdesign.fr/, it is not very clear how to bind the component using ViewChild. 

On the page it says, "By binding timer with @ViewChild('basicTimer'), you can control the timer."

In Angular 8, I tried the following:
`@ViewChild( 'basicTimer', { static: false } ) cdTimer : CdTimerComponent;`

When I try to use `this.cdTimer.start()` in the code, I'm told that this.cdTimer does not exist. I'm unable to determine the exact syntax to be able to use the timer programmatically.

Thanks for your help.

**Comment by clemdesign** [comment]
Hi, did you add the markup `#basicTimer` to the tag `<cd-timer>` like this `<cd-timer #basicTimer>` ?

**Comment by sourjya** [comment]
Thank you for your response. 

Yes - I did add the tag. The issue here is within the component typescript file. How do I instantiate the timer and call the object methods? When I try to refer it to as this.cdTimer (or whatever name you give it), TS reports that this.cdTimer is unefined. 

![image](https://user-images.githubusercontent.com/393134/71073257-953e3a00-21b2-11ea-8f1e-7ea806c8d94a.png)

**In my html:**
```
              <cd-timer #basicTimer
                format="user"
                countdown="true"
                [startTime]="7200">
                [hours]h [minutes]m [seconds]s
              </cd-timer>
```

In my class:
```
export class StandardizedTestComponent implements OnInit {

  @ViewChild( 'basicTimer', { static: false } ) cdTimer: CdTimerComponent;

  constructor() {

    // Prevent timer from starting
    this.cdTimer.autoStart = false;
  }

}
```

The error is being thrown in the line `this.cdTimer.autoStart = false;`. 

How do I instantiate the timer and access the methods like start(), stop() etc.

**Comment by clemdesign** [comment]
The timer is not yet initialized in your component constructor.

If you want to prevent starting of timer, you could implement:

```
<cd-timer #basicTimer
    format="user"
    countdown="true"
    [startTime]="7200"
    autoStart="false">
    [hours]h [minutes]m [seconds]s
</cd-timer>
```

You can bind to boolean variable if you want to control `autoStart`, but the value shall be set before initialization of cd-timer component.

When cd-timer is [initialized](https://angular.io/guide/lifecycle-hooks), you can access to methods.

**Comment by sourjya** [comment]
Thank you. By moving the cdTimer object to ngAfterViewInit(), I was able to get rid of the error.

**Comment by clemdesign** [comment]
That's depends of your needs, If you want manipulate DOM related to timer for instance.

I close this issue.

**Comment by Vishu8** [comment]
@sourjya Buddy can you explain to me how you resolved this issue in detail as I am getting *TypeError: Cannot read property 'start' of undefined* as I call the function start() to start the timer.
