### ISSUE TITLE
@ViewChild() not working

### ISSUE THREAD

**Issue by Vishu8** [clemdesign/angular-cd-timer#4]
```import { CdTimerComponent } from 'angular-cd-timer';```
```@ViewChild('basicTimer', { static: true }) basicTimer: CdTimerComponent;```

I have written this and declared it before ngOnInit and when I am calling the start function
```this.basicTimer.start();```
in OnInit and on HTML side I have written below:
```<cd-timer #basicTimer format="user" autoStart="false">[hours] h [minutes] m [seconds] s</cd-timer>```

but getting an error **ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'start' of undefined** can you help me out what's the issue here.

**Comment by clemdesign** [comment]
Please refer to solution in issue #3 .

Your component is probably not yet initiliazed. 

I close this issue.
