### ISSUE TITLE
Timer started to increase after becoming 0 when I set [countdown] to true

### ISSUE THREAD

**Issue by karthick-infinire** [clemdesign/angular-cd-timer#54]
In my application, I am using a two timer
Elapsed time: <cd-timer [startTime]="appt.elapsedTime" format="ms"></cd-timer>
Remaining time: <cd-timer [countdown]="true" [startTime]="appt.remainingTime"
                                        (onTick)="onTimeChange($event, appt)" format="ms"></cd-timer>

I am using this in for loop
Did anything I missed?

**Comment by clemdesign** [comment]
Try to set `[startTime]` to fixed value. If no problem appears, look around `appt.remainingTime` updating.

**Comment by karthick-infinire** [comment]
I tried to set [startTime] to a fixed value but it doesn't work.
Then I handled the onTick and used the stop() function for this. It worked.
