### ISSUE TITLE
angular-cd-timer/index.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by ipvinner** [clemdesign/angular-cd-timer#7]
Hello, in my project 
 "@angular/core": "^4.3.2",
 "rxjs": "^5.4.2",
"angular-cd-timer": "1.0.0",

but when I tried to add:
**import {CdTimerModule} from "angular-cd-timer";
caught error:
index.d.ts, found version 4, expected 3, resolving symbol

**Comment by clemdesign** [comment]
Hi, with this statement, I will say that you have an inconsistency between package. But I can't say you what.

More investigation shall be done. Could you share your full dependencies list please ?

**Comment by clemdesign** [comment]
Okay, try to update your rxjs to >= 5.5.0.
